name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        env:
          FB_KEY: ${{ secrets.FB_KEY }}
          FB_AUTH: ${{ secrets.FB_AUTH }}
          FB_PID: ${{ secrets.FB_PID }}
          FB_BUK: ${{ secrets.FB_BUK }}
          FB_SND: ${{ secrets.FB_SND }}
          FB_AID: ${{ secrets.FB_AID }}

        run: |
          echo "$FD_AUTH"
          npm ci
          npm run build
          touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.ALURAKUT }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true


